# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3423aadb3ba79946df78fc1c98f5987518897ab1621bc973f94ce6142cf8816592b3bb0da7ae3feceabd03332b92c0024747348e99fb21c466229cea1793191a

test:
  secret_key_base: 59cde51da160c7b814642c06b7cf267c7dc400c75a8ac14c35e2b81a53b5b01932333a403e5ae939fe8dbcbdb5c8f90ec64b1db80b8069b5d69cd13dd1e8d9ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
